(function(){
const script=document.currentScript,api=(script.dataset.apiBase||new URL(script.src).origin).replace(/\/$/,"");
const host=document.body.appendChild(document.createElement("div")),root=host.attachShadow({mode:"open"});
root.innerHTML=`<style>*{box-sizing:border-box}button,input{font:inherit}.launch{position:fixed;right:20px;bottom:20px;width:62px;height:62px;border:0;border-radius:50%;background:#1767a3;color:#fff;font-size:25px;box-shadow:0 8px 30px #0004;cursor:pointer;z-index:2147483647}.panel{position:fixed;right:20px;bottom:94px;width:min(390px,calc(100vw - 24px));height:min(610px,calc(100vh - 115px));background:#f7f9fc;border:1px solid #dbe3ee;border-radius:20px;box-shadow:0 20px 60px #10253d55;display:none;flex-direction:column;overflow:hidden;z-index:2147483647;color:#172235;font:15px/1.45 system-ui}.open{display:flex}.head{padding:17px 18px;background:linear-gradient(135deg,#102f58,#1767a3);color:#fff}.head strong{display:block;font-size:17px}.head span{opacity:.8;font-size:12px}.messages{flex:1;overflow:auto;padding:14px}.msg{padding:10px 12px;margin:7px 0;border-radius:14px;max-width:88%;white-space:pre-wrap}.bot{background:#fff;border:1px solid #e2e8f0}.user{background:#1767a3;color:#fff;margin-left:auto}.typing{opacity:.6}.actions{display:flex;gap:7px;flex-wrap:wrap}.action{border:1px solid #1767a3;color:#1767a3;background:#fff;border-radius:20px;padding:7px 11px;cursor:pointer}.sources a{font-size:12px;color:#1767a3;display:block}.composer{display:flex;padding:11px;background:#fff;border-top:1px solid #e2e8f0}.composer input{flex:1;min-width:0;border:1px solid #cbd5e1;border-radius:22px;padding:10px 13px}.composer button{border:0;background:#1767a3;color:#fff;border-radius:50%;width:42px;margin-left:7px}@media(max-width:500px){.panel{right:12px;bottom:84px;height:calc(100vh - 100px)}.launch{right:14px;bottom:14px}}</style><button class="launch" aria-label="Open AI sales assistant">✦</button><section class="panel" role="dialog"><header class="head"><strong>Systematic AI Sales Assistant</strong><span>Online · Ask in any language</span></header><main class="messages" aria-live="polite"><div class="msg bot">Hello! Ask about a service, show me a page, or arrange a call.</div></main><form class="composer"><input maxlength="4000" aria-label="Message" placeholder="How can we help?"><button aria-label="Send">➤</button></form></section>`;
const sourceStyle=document.createElement('style');sourceStyle.textContent='.sources{display:none}';root.appendChild(sourceStyle);
const panel=root.querySelector('.panel'),messages=root.querySelector('.messages'),input=root.querySelector('input'),send=root.querySelector('.composer button');let session=localStorage.getItem('sits_agent_session')||(crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)})),lastId=0,pollTimer;localStorage.setItem('sits_agent_session',session);
root.querySelector('.launch').onclick=()=>{panel.classList.toggle('open');input.focus()};
function add(text,kind){const el=document.createElement('div');el.className='msg '+kind;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
async function event(event_type,data={}){try{await fetch(api+'/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_type,session_id:session,data})})}catch(_){}}
event('visitor.page_view',{url:location.href,title:document.title});
async function pollHandover(){if(!session)return;try{const res=await fetch(`${api}/api/conversations/${session}/updates?after_id=${lastId}`);if(!res.ok)return;for(const msg of await res.json()){lastId=Math.max(lastId,msg.id);add(msg.content,'bot')}}catch(_){}}
function action(a){event('action.'+a.type,{url:a.url});if(a.type==='fill_form'){Object.entries(a.fields||{}).forEach(([name,value])=>{if(!value)return;const el=document.querySelector(`[name="${CSS.escape(name)}"],#${CSS.escape(name)}`);if(el){el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}))}});if(a.url){const url=a.url+'?session='+encodeURIComponent(session);window.open(url,'_blank','noopener')}}else if(a.url){const url=a.type==='book_meeting'?a.url+'?session='+encodeURIComponent(session):a.url;window.open(url,'_blank','noopener')}}
let sending=false;
root.querySelector('form').onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text||sending)return;sending=true;input.disabled=true;send.disabled=true;input.value='';add(text,'user');const wait=add('Thinking…','bot typing');try{const res=await fetch(api+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,session_id:session,page_url:location.href})}),data=await res.json();if(!res.ok)throw Error(data.detail||'The request failed. Please try again.');session=data.session_id;lastId=data.message_id;localStorage.setItem('sits_agent_session',session);wait.textContent=data.answer;wait.classList.remove('typing');if(data.sales_stage==='handover'&&!pollTimer)pollTimer=setInterval(pollHandover,4000);if(data.sources?.length){const box=document.createElement('div');box.className='sources';data.sources.slice(0,3).forEach(s=>{const a=document.createElement('a');a.href=s.url;a.target='_blank';a.rel='noopener';a.textContent='Source: '+s.title;box.appendChild(a)});messages.appendChild(box)}if(data.actions?.length){const box=document.createElement('div');box.className='actions';data.actions.forEach(a=>{const b=document.createElement('button');b.className='action';b.textContent=a.label;b.onclick=()=>action(a);box.appendChild(b)});messages.appendChild(box)}}catch(err){wait.textContent=err.message||'Sorry, I could not connect. Please try again.';wait.classList.remove('typing')}finally{sending=false;input.disabled=false;send.disabled=false;input.focus()}messages.scrollTop=messages.scrollHeight};
function renderStreamResult(data,wait){session=data.session_id;lastId=data.message_id;localStorage.setItem('sits_agent_session',session);wait.classList.remove('typing');if(data.sales_stage==='handover'&&!pollTimer)pollTimer=setInterval(pollHandover,4000);if(data.actions?.length){const box=document.createElement('div');box.className='actions';data.actions.forEach(a=>{const b=document.createElement('button');b.className='action';b.textContent=a.label;b.onclick=()=>action(a);box.appendChild(b)});messages.appendChild(box)}}
root.querySelector('form').onsubmit=async e=>{e.preventDefault();const text=input.value.trim();if(!text||sending)return;sending=true;input.disabled=true;send.disabled=true;input.value='';add(text,'user');const wait=add('Thinking...','bot typing');try{const res=await fetch(api+'/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,session_id:session,page_url:location.href})});if(!res.ok)throw Error('The request failed. Please try again.');const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',answer='',finished=false;while(!finished){const part=await reader.read();finished=part.done;buffer+=decoder.decode(part.value||new Uint8Array(),{stream:!finished});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='delta'){answer+=event.delta;wait.textContent=answer;wait.classList.remove('typing');messages.scrollTop=messages.scrollHeight}else if(event.type==='done'){renderStreamResult(event.data,wait)}else if(event.type==='error'){throw Error(event.data)}}}}catch(err){wait.textContent=err.message||'Sorry, I could not connect. Please try again.';wait.classList.remove('typing')}finally{sending=false;input.disabled=false;send.disabled=false;input.focus()}messages.scrollTop=messages.scrollHeight};
})();
