let adminKey='';
const key=()=>adminKey;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let leadCache=[];
async function reply(id){const message=prompt('Reply as a live sales agent:');if(!message)return;const response=await fetch(`/api/admin/conversations/${id}/reply`,{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Key':key()},body:JSON.stringify({message})});if(!response.ok)alert('Reply could not be delivered')}
async function manage(id){const lead=leadCache.find(x=>x.session_id===id);if(!lead)return;const statusInput=prompt('Status: new, contacted, qualified, proposal, won, lost, or handover',lead.crm_status);if(statusInput===null)return;const status=statusInput.trim().toLowerCase();const allowed=['new','contacted','qualified','proposal','won','lost','handover'];if(!allowed.includes(status))return alert(`Invalid status. Use one of: ${allowed.join(', ')}`);const assignedInput=prompt('Assigned sales representative',lead.assigned_to||'');if(assignedInput===null)return;const followUpInput=prompt('Follow-up (YYYY-MM-DDTHH:MM), or blank',lead.follow_up_at?.slice(0,16)||'');if(followUpInput===null)return;const follow_up_at=followUpInput.trim();if(follow_up_at&&!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(follow_up_at))return alert('Invalid follow-up date. Use YYYY-MM-DDTHH:MM, for example 2026-08-20T10:30.');const notesInput=prompt('CRM notes',lead.notes||'');if(notesInput===null)return;const response=await fetch(`/api/admin/leads/${id}`,{method:'PUT',headers:{'Content-Type':'application/json','X-Admin-Key':key()},body:JSON.stringify({status,assigned_to:assignedInput.trim()||null,follow_up_at:follow_up_at||null,notes:notesInput.trim()||null})});if(!response.ok){let detail=`CRM update failed (${response.status})`;try{const body=await response.json();detail=Array.isArray(body.detail)?body.detail.map(item=>item.msg).join('\n'):body.detail||detail}catch(_){}return alert(detail)}await load();localStorage.removeItem('sales_admin_key');alert('Lead updated successfully. Notes were saved and will appear the next time you open Manage.')}
function resetRejectedKey(response){if(response.status===401){adminKey='';document.querySelector('#dashboard').hidden=true;document.querySelector('#login').hidden=false;document.querySelector('#login-error').textContent='Your session is no longer authorized. Enter the admin API key again.';document.querySelector('#admin-key').focus();return true}return false}
async function connectCalendar(){const response=await fetch('/api/google-calendar/connect',{headers:{'X-Admin-Key':key()}}),data=await response.json();if(resetRejectedKey(response))return;if(!response.ok)return alert(data.detail||'Google setup failed');location.assign(data.authorization_url)}
async function integrationStatus(){try{const response=await fetch('/api/google-calendar/status'),data=await response.json();if(data.connected)document.querySelector('#calendar').textContent=data.spreadsheet_url?'Google Calendar + Sheets connected':'Google Calendar connected'}catch(_){}}
async function load(){document.querySelector('#error').textContent='';try{const headers={'X-Admin-Key':key()};const [d,l]=await Promise.all([fetch('/api/admin/dashboard',{headers}),fetch('/api/admin/leads',{headers})]);if(resetRejectedKey(d))return;if(!d.ok)throw Error('Dashboard access failed ('+d.status+')');const data=await d.json(),leads=await l.json();leadCache=leads;localStorage.setItem('sales_admin_key',headers['X-Admin-Key']);const labels={website_visitors:'Visitors',conversations:'Conversations',leads_generated:'Leads',conversion_rate:'Conversion %',meetings_booked_or_requested:'Meetings',messages:'Messages'};document.querySelector('#metrics').innerHTML=Object.entries(data.totals).map(([k,v])=>`<div class="metric"><span>${esc(labels[k]||k)}</span><strong>${esc(v)}</strong></div>`).join('');const max=Math.max(1,...data.popular_services.map(x=>x.count));document.querySelector('#services').innerHTML=data.popular_services.map(x=>`<div class="bar">${esc(x.name)} <b>${x.count}</b><i style="width:${x.count/max*100}%"></i></div>`).join('')||'No service data yet.';document.querySelector('#pipeline').innerHTML=Object.entries(data.lead_status).map(([k,v])=>`<div class="bar">${esc(k)} <b>${v}</b></div>`).join('')||'No conversations yet.';document.querySelector('#faqs').innerHTML=data.frequently_asked_questions.map(x=>`<div class="faq">${esc(x.question)} <b>×${x.count}</b></div>`).join('')||'No questions recorded yet.';const statRows=x=>Object.entries(x||{}).map(([k,v])=>`<div class="stat-row"><span>${esc(k.replaceAll('_',' '))}</span><b>${typeof v==='object'?esc(JSON.stringify(v)):esc(v)}</b></div>`).join('');const refresh=data.ai_performance?.knowledge_refresh||{};const aiPerformance={...data.ai_performance,knowledge_refresh:refresh.knowledge_refresh_status||'pending'};document.querySelector('#ai-performance').innerHTML=statRows(aiPerformance);document.querySelector('#sales-performance').innerHTML=statRows(data.sales_performance);document.querySelector('#temperature').innerHTML=statRows(data.lead_temperature)||'No classified leads yet.';document.querySelector('#leads').innerHTML=leads.map(x=>`<tr style="${x.follow_up_overdue?'background:#fff1f1':''}"><td><b>${esc(x.name||'Unnamed')}</b><br><small>${esc(x.email||x.phone||'')}</small></td><td>${(x.services||[]).map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</td><td>${x.score} / ${esc(x.temperature)}</td><td><span class="tag">${esc(x.crm_status)}</span></td><td>${esc(x.assigned_to||'Unassigned')}<br><small>${x.follow_up_at?esc(new Date(x.follow_up_at).toLocaleString()):'No reminder'}</small></td><td><button onclick="manage('${esc(x.session_id)}')">Manage</button> <button onclick="reply('${esc(x.session_id)}')">Reply</button></td></tr>`).join('')}catch(e){document.querySelector('#error').textContent=e.message}}
document.querySelector('#calendar').onclick=connectCalendar;
document.querySelector('#refresh').onclick=load;
document.querySelector('#login-form').onsubmit=async event=>{event.preventDefault();const input=document.querySelector('#admin-key'),error=document.querySelector('#login-error'),button=event.submitter;adminKey=input.value.trim();error.textContent='';button.disabled=true;button.textContent='Checking...';try{const response=await fetch('/api/admin/auth',{headers:{'X-Admin-Key':adminKey}});if(!response.ok){adminKey='';error.textContent=response.status===401?'Incorrect admin API key.':'Dashboard authentication is unavailable.';input.select();return}localStorage.removeItem('sales_admin_key');document.querySelector('#login').hidden=true;document.querySelector('#dashboard').hidden=false;input.value='';await load();localStorage.removeItem('sales_admin_key');integrationStatus()}catch(_){adminKey='';error.textContent='Could not connect to the dashboard API.'}finally{button.disabled=false;button.textContent='Open dashboard'}};
